# Generated by Django 3.2.8 on 2021-10-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('release_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(null=True)),
                ('next_day_delivery', models.BooleanField()),
                ('environment_friendly', models.BooleanField()),
                ('category', models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids')], max_length=8, null=True)),
                ('inventory', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('release_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoes', to='product.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='product.shoe')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.shoe')),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue')], max_length=8, null=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='product.shoe')),
            ],
        ),
    ]
