# Generated by Django 3.2.8 on 2021-10-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211011_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='colour',
            new_name='colour_name',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='size_number',
        ),
        migrations.RemoveField(
            model_name='colour',
            name='shoe',
        ),
        migrations.RemoveField(
            model_name='size',
            name='shoe',
        ),
        migrations.AddField(
            model_name='shoe',
            name='sizes',
            field=models.ManyToManyField(to='product.Size'),
        ),
    ]
