# Generated by Django 3.2.8 on 2021-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
